name: Publish to PyPI
on:
  push:
    branches:
      - main  # Change this to your main branch name
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change this to the desired Python version

      - name: Build and publish package
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
          python3 -m pip install --upgrade twine
          python3 -m twine upload --repository testpypi dist/*
