name: Dependent Workflow

on:
  push:
    branches:
      - main

jobs:
  step1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        id: step1
        run: |
          # Add your Step 1 logic here
          echo "Step 1 Output" >> step1_output.txt

    outputs:
      output1: ${{ steps.step1.outputs.output1 }}

  step2:
    needs: step1
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        id: step2
        run: |
          # Add your Step 2 logic here
          # Use the output from Step 1 using ${{ needs.step1.outputs.output1 }}
          echo "Step 2 Input: ${{ needs.step1.outputs.output1 }}"
          echo "Step 2 Output" >> step2_output.txt

    outputs:
      output2: ${{ steps.step2.outputs.output2 }}

  step3:
    needs: step2
    runs-on: ubuntu-latest

    steps:
      - name: Step 3
        id: step3
        run: |
          # Add your Step 3 logic here
          # Use the output from Step 2 using ${{ needs.step2.outputs.output2 }}
          echo "Step 3 Input: ${{ needs.step2.outputs.output2 }}"
          echo "Step 3 Output" >> step3_output.txt

    outputs:
      output3: ${{ steps.step3.outputs.output3 }}
