name: Dependent Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add your build and test steps here
      
      - name: Publish artifact
        id: publish-artifact
        run: |
          # Add the commands to publish the artifact
          # This step generates an artifact that will be used in the next job
          echo "Publishing artifact..."
          echo "/path/to/artifact.zip" > ${{ runner.workspace }}/artifact-path
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download artifact
        run: |
          # Download the artifact generated in the previous job
          echo "Downloading artifact..."
          echo "Artifact path: $(cat ${{ runner.workspace }}/artifact-path)"
      
      # Add your deployment steps here
